main.out: Main.o NegociosAsociados.o Personas.o Oficina.o Repartidores.o Productos.o Clientes.o Ordenes.o
	g++ Main.o NegociosAsociados.o Personas.o Oficina.o Repartidores.o Productos.o Clientes.o Ordenes.o -o main.out
 


main.o: Main.cpp NegociosAsociados.cpp  Personas.cpp Oficina.cpp Repartidores.cpp Productos.cpp Clientes.cpp Ordenes.cpp
	g++ Main.cpp
